export { default as Hero } from './Hero'
export { default as Features } from './Features'
export { default as Gallery } from './Gallery'
export { default as Pricing } from './Pricing'
export { default as Reviews } from './Reviews'
export { default as Contact } from './Contact'